### ISSUE TITLE
Feedback for the mapping tool

### ISSUE THREAD

**Issue by DavidZtako** [AmberYYYYYYYY/Cuisine-Filter#2]
Hi Amber, David's here! I've tested your mapping tool and there are some feedbacks.

**Comments:**

1. The component works well on my OSM file and the visualized result looks amazing. 

2. The sequences of the component are pretty clear. I can easily find where to input data source, where to find geometry controller and where is the colour controller is. Great work!

**And there are some ideas about improvement as well** (maybe you have done these already, anyway :D)

1.	The annotations could be a little bit clearer. For example, I can easily understand French cuisine in blue, Japanese cuisine in purple, but I’m a little confused about what the density is for these three features. 

2.	I just assume the size of yellow geometries represents overall density for all types of cuisine. Then this assumption leads to the result that French and Japanese cuisine should be subsets of the overall cuisine (if the areas are the same, the density of French and Japanese cuisine may be always smaller or equal to the density of overall cuisine). I’m probably wrong, but if the number of French and Japanese cuisines is smaller than the sum, then the size of the geometries might need some more consideration.

![ViewCapture20210912_234618](https://user-images.githubusercontent.com/88956151/132990084-7d9abefe-00be-4be5-8d7a-365912f0e45d.jpg)

Image_01: The density of Japanese cuisine looks larger than the overall density. 

All in all, the visualization style is amazing, annotation is clear. Great works!

**Comment by AmberYYYYYYYY** [comment]
Hi David, 
Thank you so much for all these value able suggestions!  The yellow geometry has been changed to another kind of cuisine [is Italian cuisine on my map but you can choose whatever you want] because the correct display of overall cuisine is around ten times larger than Japanese and French... You can imagine how messy my map looks when I make it right. LOL  

And yes, I add many annotations in my v0.7 version, including the proportion of different cuisines, the total area of food courts, closest distance... These could use to make comparisons across cities or time. : )

![overall](https://user-images.githubusercontent.com/88841215/134684261-431a58b2-3d54-4ecb-bbbf-98c894f1061a.png)
![10](https://user-images.githubusercontent.com/88841215/134684109-80dd8ca8-e79c-4598-ad05-347bffaeec02.png)

You could try it here: https://github.com/AmberYYYYYYYY/Test-mappingtoo
